GET http://localhost:8000/api/users

###
GET http://localhost:8000/api/users/7

###
POST http://localhost:8000/api/users HTTP/1.1
User-Agent: rest-client
content-type: application/json

{
    "name": "Bobo",
    "skills": [
        {
            "id": 3,
            "name": "Java",
            "vote": 3
        },
        {
            "id": 4,
            "name": "Php",
            "vote": 9
        }
    ]
}

###
PUT http://localhost:8000/api/users/4 HTTP/1.1
User-Agent: rest-client
content-type: application/json

{
    "name": "Alfred"
}

###
DELETE http://localhost:8000/api/users/1 HTTP/1.1
User-Agent: rest-client
content-type: application/json
